job/urls.py
from django.urls import path

from . import views

app_name='lion'

urlpatterns = [    
    path("", views.JobLV.as_view(), name="index"),
    path("detail/<int:pk>/", views.JobDV.as_view(), name="detail"),
    path("upload/", views.image_upload_view, name='upload'),
]

job_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("job.urls")),    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

job/models.py
from django.db import models

# Create your models here.
# Person - 이름, 전문분야, 증명사진

class Person(models.Model):    
    name = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)    
    image = models.ImageField(upload_to='images/') # 이 부분이 이미지 저장

job/forms.py
from django import forms
from .models import Person

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['name', 'subject', 'image']

job/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Person
from django.http import HttpResponse
# Create your views here.

class JobLV(ListView):
    model= Person
    
class JobDV(DetailView):
    model= Person

from .forms import PersonForm
def image_upload_view(request):
    # Get방식으로 들어오면 입력 폼을 보내주고
    if request.method=='GET':
        form = PersonForm()
        context = {'form':form}
        return render(request, 'job/data_write.html', context)
    # Post 방식으로 들어오면 저장하기
    elif request.method=='POST':
        form = PersonForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('lion:index')
        else:return HttpResponse("문제가 있네요") 
    

job/templates/job/data_write.html
<h1>이력서 정보를 입력해 주세요</h1>
<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="input-group mb-3">
    {{form.as_table}}
    </div>
    <input type="submit" value="저장" class="btn btn-primary">
</form>

job/templates/job/person_detail.html
<h1>Person Detail</h1>
{{object.name}}
{{object.subject}}
<img src="{{object.image.url}}" alt="">

job/templates/job/person_list.html
<h1>Person List</h1>
{% for person in object_list %}
<a href="{% url 'lion:detail' person.id %}">{{person.name}} ==== {{person.subject}}</a>
<img src="{{person.image.url}}" alt="" width="100px">
{% endfor %}